# Config for Flagwix store — uoy-flagwix-bulk-edit app

client_id = "c4840c69f4aa4490612f79d4a6494c0e"
name = "uoy-flagwix-bulk-edit"
application_url = "https://uoy-flagwix-bulk-edit.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
scopes = "write_products,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://uoy-flagwix-bulk-edit.onrender.com/auth/callback" ]
