# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c011a2792436213134d604517505948"
name = "UOY Bulk Editor Local"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "https://example.com/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://example.com/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://example.com/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]
