# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2182ce328efa7502b05f8142e93b7209"
name = "UOY Bulk Editor Custom"
application_url = "https://uoy-bulk-editor.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://uoy-bulk-editor.onrender.com/auth/callback" ]

[webhooks]
api_version = "2026-07"
